name: Despliegue en Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v2

    - name: Instalar Azure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y azure-cli



    - name: Iniciar sesión en Azure
      run: az login --service-principal --username ${{ secrets.APP_ID }} --password ${{ secrets.PASSWORD }} --tenant ${{ secrets.TENANT }}


    - name: Iniciar Docker Build y Push
      uses: azure/docker-login@v1
      with:
        login-server: pythontestcr.azurecr.io
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    - name: Construir y etiquetar la imagen Docker
      run: |
        docker build -t pythontestcr.azurecr.io/pythonapp:$GITHUB_RUN_NUMBER .
        docker push pythontestcr.azurecr.io/pythonapp:$GITHUB_RUN_NUMBER

    - name: Desplegar en Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myAppPythonTest'
        images: 'pythontestcr.azurecr.io/pythonapp:$GITHUB_RUN_NUMBER'


